adobe/helix-tools-website

fstab.yaml
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--helix-admin-website--adobe.hlx.live/
- After: https://init--helix-admin-website--adobe.hlx.live/
=> chore: update fstab

tools/log-viewer/index.html, tools/log-viewer/scripts.js, tools/log-viewer/styles.css
dependent on #6 
Test URLs:
- Before: https://main--helix-admin-website--adobe.hlx.live/tools/log-viewer/index.html
- After: https://log-viewer--helix-tools-website--adobe.aem.page/tools/log-viewer/index.html
=> feat: log viewer

tools/rum/admin/orgs.css, tools/rum/admin/orgs.html, tools/rum/admin/orgs.js, tools/rum/admin/store.js
Test URLs:
- After: https://feat-rum-org-key-mgr--helix-tools-website--adobe.hlx.live/tools/rum/admin/org.html
=> Add Rum Org manager.

tools/log-viewer/index.html, tools/log-viewer/scripts.js
Fix #15 
Test URLs:
- Before: https://main--helix-tools-website--adobe.hlx.live/tools/log-viewer/index.html
- After: https://log-viewer-update--helix-tools-website--adobe.hlx.live/tools/log-viewer/index.html
=> Updated to use site url instead of gh url for HLX5 repo less sites

tools/log-viewer/scripts.js
Fix #18
Test URLs:
- Before: https://main--helix-tools-website--adobe.hlx.live/log-viewer
- After: https://log-viewer-url-check--helix-tools-website--adobe.hlx.live/log-viewer
=> added fix to check if aem.page exists before linking the end user to .page

tools/rum/admin/orgs.js
Test URLs:
- After: https://bug-rum-mgr-enhance--helix-tools-website--adobe.hlx.live/tools/rum/admin/orgs.html
=> Rmeove duplicate rum call.

tools/log-viewer/scripts.js, tools/push-invalidation/scripts.js
before: https://main--helix-tools-website--adobe.aem.page/log-viewer
after: https://dupe-rums--helix-tools-website--adobe.aem.page/log-viewer
=> removed dupe calls to rum

styles/styles.css, tools/bulk/index.html, tools/bulk/scripts.js, tools/bulk/styles.css
Test URLs:
- Before: https://main--helix-tools-website--adobe.hlx.live/tools/bulk/index.html
- After: https://bulk-ops--helix-tools-website--adobe.hlx.live/tools/bulk/index.html
=> refactor: bulk ops styles

blocks/cards/cards.css
Test URLs:
- Before: https://main--helix-tools-website--adobe.hlx.live/
- After: https://tone-down--helix-tools-website--adobe.hlx.live/
=> tone down images new variant

tools/rum/admin/orgs.css, tools/rum/admin/orgs.html, tools/rum/admin/orgs.js, tools/rum/admin/store.js
Test URLs:
- Before: https://main--helix-tools-website--adobe.hlx.live/tools/rum/admin/orgs.html?org=adobe
- After: https://rum-org-updates--helix-tools-website--adobe.hlx.live/tools/rum/admin/orgs.html?org=adobe
=> fix: style fixes, add helixOrgs on create/update modals

tools/log-viewer/scripts.js
Use crn-com (last 3 days) to test
Fix #31 
Test URLs:
- Before: https://main--helix-tools-website--adobe.hlx.live/log-viewer
- After: https://31-tccc-error--helix-tools-website--adobe.hlx.live/log-viewer
=> fixed issue when route is sitemap

sidekick/config.schema.json
Add sidekick config schema
Test URLs:
- Before: https://main--helix-tools-website--adobe.hlx.live/
- After: https://sidekick-config-schema--helix-tools-website--adobe.hlx.live/
=> fix: add sidekick config schema

tools/log-viewer/index.html, tools/log-viewer/scripts.js, tools/log-viewer/styles.css
Fix #40 
Test URLs:
- Before: https://main--helix-tools-website--adobe.hlx.live/log-viewer
- After: https://40-show-user-column--helix-tools-website--adobe.hlx.live/log-viewer
=> Show user column by default

tools/log-viewer/scripts.js
Fix #47 
Test URLs:
- After: https://logs-links--helix-tools-website--adobe.hlx.live/tools/log-viewer/index.html
=> fix: links back to site should go to same domain as input url

tools/log-viewer/scripts.js
Fix #48 
Test URLs:
- Before: https://main--helix-tools-website--adobe.hlx.live/tools/log-viewer/index.html
- After: https://logs-sort--helix-tools-website--adobe.hlx.live/tools/log-viewer/index.html
=> feat: ensure all logs are fetched for entire timespan

tools/log-viewer/scripts.js, utils/prism/prism.css, utils/prism/prism.js
enable prism syntax highlighting on admin details
Test URLs:
- Before: https://main--helix-tools-website--adobe.aem.live/tools/log-viewer/index.html
- After: https://syntax-highlight--helix-tools-website--adobe.aem.live/tools/log-viewer/index.html
=> feat: syntax highlight

tools/log-viewer/scripts.js
To test:
* make sure you are not! logged in via Sidekick
* open log viewer
* enter org, site and click submit
* before generic error now there is correct error for 401 with sidekick link
Test URLs:
Before: https://main--helix-tools-website--adobe.aem.live/log-viewer/index.html
After: https://log-auth-msg--helix-tools-website--adobe.aem.live/tools/log-viewer/index.html
=> chore: improve auth error handling

tools/log-viewer/index.html
Test URLs:
- Before: https://main--helix-tools-website--adobe.aem.live/log-viewer
- After: https://how-to-use--helix-tools-website--adobe.aem.live/log-viewer
=> adding instructions on how to login to view logs

tools/push-invalidation/scripts.js
https://main--helix-tools-website--adobe.hlx.live/tools/push-invalidation/index.html?type=cloudfront
https://cloudfront-fix--helix-tools-website--adobe.aem.page/tools/push-invalidation/index.html?type=cloudfront
=> chore: cloudfront display error

sidekick/config.schema.json
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--helix-tools-website--adobe.hlx.live/
- After: https://sidekick-schema-update--helix-tools-website--adobe.hlx.live/
=> fix: update sidekick schema

tools/log-viewer/index.html, tools/log-viewer/scripts.js, utils/config/config.js
synchronize https://github.com/adobe/helix-labs-website/pull/95 to tools
https://config-sk--helix-tools-website--adobe.aem.live/tools/log-viewer/index.html
=> chore: port sidekick projects config from labs

tools/bulk/bulk.js, tools/bulk/index.html, tools/bulk/scripts.js
adding more operations to bulk tools... (bulk unpublish and unpreview)
https://bulk-unpublish--helix-tools-website--adobe.aem.page/tools/bulk/index.html
=> [feat] add more operations to to bulk tools

styles/styles.css, tools/oversight/explorer.html, tools/oversight/rum-slicer.css, tools/rum/explorer.html, tools/rum/rum-slicer.css
Cleanup of the rum and oversight tools when moved to this site 
Test URLs:
Oversight Explorer
- Before: https://main--helix-tools-website--adobe.aem.live/tools/oversight/explorer.html?domain=labs.aem.live&filter=&view=month&=performance&checkpoint=click&domainkey=XXXX
- After: https://rum-style-cleanup--helix-tools-website--adobe.aem.live/tools/oversight/explorer.html?domain=labs.aem.live&filter=&view=month&=performance&checkpoint=click&domainkey=XXXX
RUM Explorer
- Before: https://main--helix-tools-website--adobe.aem.live/tools/rum/explorer.html?domain=labs.aem.live&filter=&view=month&=performance&checkpoint=click&domainkey=XXXX
- After: https://rum-style-cleanup--helix-tools-website--adobe.aem.live/tools/rum/explorer.html?domain=labs.aem.live&filter=&view=month&=performance&checkpoint=cl …
=> rum styling cleanup

404.html, head.html, tools/bulk/index.html, tools/log-viewer/index.html, tools/push-invalidation/index.html
Test URLs:
- Before: https://main--helix-tools-website--adobe.aem.live/
- After: https://csp-nonce--helix-tools-website--adobe.aem.live/
- Before: https://main--helix-tools-website--adobe.aem.live/tools/push-invalidation/index.html
- After: https://csp-nonce--helix-tools-website--adobe.aem.live/tools/push-invalidation/index.html
- Before: https://main--helix-tools-website--adobe.aem.live/tools/log-viewer/index.html
- After: https://csp-nonce--helix-tools-website--adobe.aem.live/tools/log-viewer/index.html
- Before: https://main--helix-tools-website--adobe.aem.live/tools/bulk/index.html
- After: https://csp-nonce--helix-tools-website--adobe.aem.live/tools/bulk/index.html
=> feat: CSP nonce + strict-dynamic

sidekick/config.schema.json
- https://sk-config-schema-sync--helix-tools-website--adobe.hlx.page/
=> chore: sync with schema in helix-config-storage

tools/log-viewer/index.html, tools/log-viewer/scripts.js, tools/log-viewer/styles.css
Test URLs:
- Before: https://main--helix-tools-website--adobe.aem.live/tools/log-viewer/index.html
- After: https://ip-column--helix-tools-website--adobe.aem.live/tools/log-viewer/index.html
=> feat: add ip column

tools/log-viewer/index.html
Fix #<gh-issue-id>
Test URLs:
- Before: https://main--helix-tools-website--adobe.aem.live/
- After: https://trieloff-patch-1--helix-tools-website--adobe.aem.live/
=> fix(log-viewer): fix typo

404.html, head.html, tools/bulk/index.html, tools/log-viewer/index.html, tools/push-invalidation/index.html
Test URLs:
- Before: https://main--helix-tools-website--adobe.aem.live/
- After: https://move-to-http-header--helix-tools-website--adobe.aem.live/
=> fix: Rename "move-as-header" to "move-to-http-header"

widgets/bot-info/bot-info.css, widgets/bot-info/bot-info.html, widgets/bot-info/bot-info.js
https://bot-info-setup--helix-tools-website--adobe.hlx.live/bot/setup?org=aemtutorial&site=mysite&user=lighthouse100@gmail.com&url=https://content.da.live/aemtutorial/mysite
https://bot-info-setup--helix-tools-website--adobe.hlx.live/bot/setup?org=aemtutorial
=> [code-sync] better info setup

blocks/profile/profile.css, blocks/profile/profile.js, blocks/profile/profile.svg
URL: https://profile-sync--helix-tools-website--adobe.aem.page/tools/log-viewer/index.html
=> chore: sync profile block between labs and tools

blocks/profile/profile.js
URL: https://force-ops-mode--helix-tools-website--adobe.aem.page/tools/log-viewer/index.html
=> chore: force ops mode
